language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
language: java
install: ant deps

dist: xenial
language: java
addons:
  apt:
    packages:
      - ant

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open
