language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools #
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-26
    - add-on
    - extra
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

script: ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)
